apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_PASSWORD
              name: dbconfig
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: dbconfig
        image: mysql:latest
        name: mysqldb
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
